server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-management?serverTimezone=GMT%2b8  # \u5317\u4EAC\u65F6\u95F4
    username: root
    password: 123456 # \u6539\u6210\u81EA\u5DF1\u7684\u5BC6\u7801

mybatis:
  mapper-locations: classpath:mapper/*.xml
